#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    
    if n%2:
        print('Weird')
    elif not n%2 and n in [2,3,4,5]:
        print('Not Weird')
    elif n%2==0 and n in [i for i in range(6,21)]:
        print('Weird')
    elif n%2==0 and n>20:
        print('Not Weird')
